import type { AdditionalFeature, Library, MainFeature } from "./types";

export const allLib: Library[] = [
	{
		name: "Chakra UI",
		url: "https://chakra-ui.com/",
		logo: "chakra-ui.svg",
		repoOwner: "chakra-ui",
		repoName: "chakra-ui",
		categories: ["UI Framework", "Design System", "Accessible"],
		packageName: "chakra-ui",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Mantine",
		url: "https://mantine.dev/",
		logo: "mantine.svg",
		repoOwner: "mantinedev",
		repoName: "mantine",
		categories: ["UI Framework", "Design System", "Modern"],
		packageName: "@mantine/core",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Material UI",
		url: "https://mui.com/",
		logo: "mui.svg",
		repoOwner: "mui",
		repoName: "material-ui",
		categories: ["UI Framework", "Design System", "Enterprise"],
		packageName: "@mui/material",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Tailwind CSS",
		url: "https://tailwindcss.com/",
		logo: "tailwindcss.svg",
		repoOwner: "tailwindlabs",
		repoName: "tailwindcss",
		categories: ["CSS Framework", "Utility First"],
		packageName: "tailwindcss",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Ant Design",
		url: "https://ant.design/",
		logo: "ant-design.svg",
		repoOwner: "ant-design",
		repoName: "ant-design",
		categories: ["UI Framework", "Design System", "Enterprise"],
		packageName: "@ant-design/icons",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Framer Motion",
		url: "https://www.framer.com/motion/",
		logo: "framer-motion.svg",
		repoOwner: "framer",
		repoName: "motion",
		categories: ["Animation", "Interactive"],
		packageName: "framer-motion",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Radix UI",
		url: "https://www.radix-ui.com/",
		logo: "radix-ui.svg",
		repoOwner: "radix-ui",
		repoName: "primitives",
		categories: ["Headless UI", "Accessible", "Primitives"],
		packageName: "radix-ui",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Shadcn UI",
		url: "https://ui.shadcn.com/",
		logo: "shadcn-ui.svg",
		repoOwner: "shadcn",
		repoName: "ui",
		categories: ["Component Library", "Modern", "Customizable"],
		packageName: "@shadcn/ui",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Next UI",
		url: "https://nextui.org/",
		logo: "nextui.svg",
		repoOwner: "nextui-org",
		repoName: "nextui",
		categories: ["UI Framework", "Modern", "Accessible"],
		packageName: "@nextui-org/react",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "DaisyUI",
		url: "https://daisyui.com/",
		logo: "daisyui.svg",
		repoOwner: "saadeghi",
		repoName: "daisyui",
		categories: ["Tailwind Components", "Theme System"],
		packageName: "daisyui",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "Headless UI",
		url: "https://headlessui.com/",
		logo: "headless-ui.svg",
		repoOwner: "tailwindlabs",
		repoName: "headlessui",
		categories: ["Headless UI", "Accessible", "Primitives"],
		packageName: "@headlessui/react",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "React Spring",
		url: "https://react-spring.dev/",
		logo: "react-spring.svg",
		repoOwner: "pmndrs",
		repoName: "react-spring",
		categories: ["Animation", "Interactive"],
		packageName: "@react-spring/web",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "React Aria",
		url: "https://react-spectrum.adobe.com/react-aria/",
		logo: "react-aria.svg",
		repoOwner: "adobe",
		repoName: "react-spectrum",
		categories: ["Headless UI", "Accessible", "Adobe"],
		packageName: "react-aria",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "React Select",
		url: "https://react-select.com/",
		logo: "react-select.svg",
		repoOwner: "JedWatson",
		repoName: "react-select",
		categories: ["Form Components", "Accessible"],
		packageName: "react-select",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "HeroUI",
		url: "https://www.heroui.com/",
		logo: "hero-ui.svg",
		repoOwner: "heroui-inc",
		repoName: "heroui",
		categories: ["UI Components", "Validation"],
		packageName: "@heroui/react",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
	{
		name: "React Bootstrap",
		url: "https://react-bootstrap.github.io/",
		logo: "react-bootstrap.svg",
		repoOwner: "react-bootstrap",
		repoName: "react-bootstrap",
		categories: ["UI Components", "Validation"],
		packageName: "react-bootstrap",
		features: {
			main: [],
			additional: [],
		},
		stars: 0,
		totalDownloads: 0,
	},
].map((library, index) => ({ ...library, id: index + 1 }));

console.log(allLib);

export const mainFeatures = [
	"Styled",
	"Unstyled",
	"Imported",
	"Copy Paste",
	"Components",
	"CSS Only",
	"Free",
	"CSS-in-JS",
	"Tailwind Based",
] as const satisfies MainFeature[];

export const additionalFeatures = [
	"Fully Accessible",
	"Built-in Themes",
	"Theme Generator",
	"Dark Mode",
	"Semantic Colors",
	"Figma files",
	"Official",
	"Public Roadmap",
	"RTL Support",
	"Fully Typed",
	"Form Helpers",
] as const satisfies AdditionalFeature[];
