export type Library = {
  name: string
  subName?: string
  logo: string
  logoDark?: string // only if the logo differs in Dark Mode
  url: string
  repoOwner?: string
  repoName?: string
  package?: string
  filterMatchings: any[]
  componentMatchings: any[]
  nbStars?: number // filled later
  nbDownloads?: number // filled later
}

export const libraries: Array<Library> = [
  {
    name: "Headless UI",
    repoOwner: "tailwindlabs",
    repoName: "headlessui",
    package: "@headlessui/vue",
    logo: "headlessui.svg",
    url: "https://headlessui.com/",
    componentMatchings: [
      "Dropdown",
      "Command Palette",
      "Toggle",
      "Accordion",
      "Modal",
      "Popover",
      "Radio",
      "Tabs",
    ],
    filterMatchings: [
      { id: "FUnstyled" },
      { id: "FComponents" },
      { id: "FImported" },
      { id: "FTailwind" },
      { id: "FAccessible" },
      { id: "FFree" },
      { id: "FOfficial" },
      { id: "FVue" },
    ],
  },
  {
    name: "Tailwind UI",
    subName: "on top of Headless UI",
    logo: "tailwind.svg",
    url: "https://tailwindui.com",
    componentMatchings: [
      "Popover",
      "Select",
      "Input",
      "Textarea",
      "Radio",
      "Checkbox",
      "Toggle",
      "Modal",
      "Alert",
      "Pagination",
      "Tabs",
      "Vertical Navigation",
      "Slideover",
      "Breadcrumb",
      "Steps",
      "Command Palette",
      "Toast",
      "Avatar",
      "Badge",
      "Dropdown",
      "Button",
      "Divider",
      "Container",
      "Card",
      "Calendar",
    ],
    filterMatchings: [
      { id: "FStyled" },
      { id: "FPasted" },
      { id: "FComponents" },
      { id: "FTailwind" },
      { id: "FAccessible" },
      { id: "FOfficial" },
    ],
  },
  {
    name: "Daisy UI",
    repoOwner: "saadeghi",
    repoName: "daisyui",
    package: "daisyui",
    logo: "daisyui.svg",
    url: "https://daisyui.com",
    componentMatchings: [
      "Accordion",
      "Alert",
      "Avatar",
      "Badge",
      "Bottom Tabs",
      "Breadcrumb",
      "Button",
      "Card",
      "Carousel",
      "Chat Bubble",
      "Checkbox",
      "Divider",
      "File Input",
      "Indicator",
      "Input",
      "Keyboard Key",
      "Vertical Navigation",
      "Mockup",
      "Modal",
      "Pagination",
      "Progress",
      "Radio",
      "Range",
      "Rating",
      "Select",
      "Slideover",
      "Stack",
      "Steps",
      "Swap",
      "Tabs",
      "Table",
      "Textarea",
      "Toggle",
      "Tooltip",
      "Popover",
    ],
    filterMatchings: [
      { id: "FStyled" },
      { id: "FImported" },
      { id: "FCSS" },
      { id: "FTailwind" },
      { id: "FFree" },
      { id: "FBuiltinThemes" },
      { id: "FThemeGenerator" },
      { id: "FSemanticColors" },
      { id: "FDarkMode" },
      { id: "FRTLSupport" },
    ],
  },
  {
    name: "Flowbite Vue",
    logo: "flowbite-vue.svg",
    url: "https://flowbite-vue.com",
    repoOwner: "themesberg",
    repoName: "flowbite", // rather than flowbite-vue to have relevant start number
    package: "flowbite-vue",
    componentMatchings: [
      "Accordion",
      "Alert",
      "Avatar",
      "Breadcrumb",
      "Button",
      "Badge",
      "Card",
      "Carousel",
      "Dropdown",
      "Pagination",
      "Progress",
      "Rating",
      "Table",
      "Tabs",
      "Timeline",
      "Tooltip",
      "Modal",
      "Vertical Navigation",
      "Input",
      "File Input",
      "Checkbox",
      "Select",
      "Toast",
      "Toggle",
      "Textarea",
      "Range",
      "Radio",
    ],
    filterMatchings: [
      { id: "FStyled" },
      { id: "FComponents" },
      { id: "FTailwind" },
      { id: "FFree" },
      { id: "FFigma" },
      { id: "FVue" },
    ],
  },
  {
    name: "Ark UI",
    logo: "arkui.svg",
    url: "https://ark-ui.com",
    repoOwner: "chakra-ui",
    repoName: "ark",
    package: "@ark-ui/vue",
    componentMatchings: [
      "Accordion",
      "Avatar",
      "Carousel",
      "Checkbox",
      "Color Picker",
      "Date Picker",
      "Modal", // As Dialog
      "Input", // As Number Input and Pin Input
      "Input Chips", // As Tags Input
      "File Input", // As File Upload
      "Pagination",
      "Popover",
      "Progress", // Circular and Linear
      "QR Code",
      "Radio", // As Radio Group
      "Rating", // As Rating Group
      "Select",
      "Signature Pad",
      "Range",
      "Panel Splitter", // As Splitter
      "Steps",
      "Tabs",
      "Toast",
      "Toggle", // As Switch
      "Toggle Button", // As Toggle
      "Tooltip",
      "Tree", // As Tree View
    ],
    filterMatchings: [
      { id: "FUnstyled" },
      { id: "FImported" },
      { id: "FComponents" },
      { id: "FFree" },
      { id: "FAccessible" },
      { id: "FRoadmap" }, // https://ark-ui.canny.io
      { id: "FTyped" },
      { id: "FVue" },
    ],
  },
]
